### ISSUE TITLE
Implement HDL code generator

### ISSUE THREAD

**Issue by DmitrySoshnikov** [DmitrySoshnikov/hdl-js#17]
The [code generator](https://github.com/DmitrySoshnikov/hdl-js/tree/master/src/generator) is an inverse procedure for parsing: having an AST, we need to generate HDL code.

This will be used to generate HDL specs from gate instances, and exporting a gate built in the UI interface to an HDL file.

```js
const hdl = require('hdl-js');
const ast = hdl.parseFile('./examples/And.hdl');

const {generator} = hdl;

// Gives a code close to the original ./examples/And.hdl
const hdlCode = generator.fromAST(ast);

console.log(hdlCode);

/*

Output:

CHIP And {

  IN a, b;
  OUT out;

  PARTS:

  Nand(a=a, b=b, out=n);
  Nand(a=n, b=n, out=out);
}

*/
```

The generated code should be readable and pretty-printed with 2 spaces indentation.

Example of a very similar generator in the `regexp-tree` project: https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/generator/index.js Basically need to handle each AST node type, and return string representation of it.

**Comment by rhedshi** [comment]
Claimed
